/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponenteTareaManolo {
        "apiUrl": string;
    }
}
declare global {
    interface HTMLComponenteTareaManoloElement extends Components.ComponenteTareaManolo, HTMLStencilElement {
    }
    var HTMLComponenteTareaManoloElement: {
        prototype: HTMLComponenteTareaManoloElement;
        new (): HTMLComponenteTareaManoloElement;
    };
    interface HTMLElementTagNameMap {
        "componente-tarea-manolo": HTMLComponenteTareaManoloElement;
    }
}
declare namespace LocalJSX {
    interface ComponenteTareaManolo {
        "apiUrl"?: string;
    }
    interface IntrinsicElements {
        "componente-tarea-manolo": ComponenteTareaManolo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "componente-tarea-manolo": LocalJSX.ComponenteTareaManolo & JSXBase.HTMLAttributes<HTMLComponenteTareaManoloElement>;
        }
    }
}
